orbs:
  react: thefrontside/react@0.2.0
  cypress: cypress-io/cypress@1
version: 2.1
workflows:
  build-and-test:
    jobs:
      - react/install
      - react/eslint:
          requires:
            - react/install
      - react/test:
          requires:
            - react/install
      - react/coverage:
          requires:
            - react/install
      - cypress/run:
          requires:
            - react/test
          executor: cypress/browsers-chrome69
          browser: chrome
          start: npm start
          yarn: true